using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Assets.script.model;

namespace Assets.script.defaultData
{
    public class CharacterDefaultSkill
    {
        public List<Skill> warriorUnobtained = new List<Skill>()
        {
            new Skill()
            {
                name = "Heal 1",
                power = 0,
                type = "support",
                description = "Heal 30% HP for an ally. Require : Level 10",
                hpGain = 0.3f,
                mpGain = -3f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = false,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Defend Buff",
                power = 0,
                type = "buff",
                description = "Increase defend for an ally for 3 turns. Require : Level 15",
                hpGain = 0,
                mpGain = -8f,
                isAtkBuff = false,
                isDefBuff = true,
                isMultiTarget = false,
                isTargetEnemy = false,
                remainTurn = 3,
            },
            new Skill()
            {
                name = "Super Slash 2",
                power = 70,
                type = "physic",
                description = "Deal light physic damage to all enemies. Require : Level 20",
                hpGain = 0,
                mpGain = -10f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = true,
                isTargetEnemy = true,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Regeneration 1",
                power = 0,
                type = "passive",
                description = "Heal 2% of max Hp each turn. Require : Level 25",
                hpGain = 0.02f,
                mpGain = 0,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = false,
                remainTurn = 999,
            },
            new Skill()
            {
                name = "Super Slash 3",
                power = 90,
                type = "Physic",
                description = "Deal heavy physic damage to an enemy. Require : Level 30",
                hpGain = 0,
                mpGain = -8f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = true,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Toxic 3",
                power = 90,
                type = "toxic",
                description = "Deal heavy toxic damage to an enemy. Require : Level 35",
                hpGain = 0,
                mpGain = -24f,
                isAtkBuff = false,
                isDefBuff = true,
                isMultiTarget = true,
                isTargetEnemy = false,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "defend buff plus",
                power = 0,
                type = "buff",
                description = "increase defend for all allies. Require : Level 40",
                hpGain = 0,
                mpGain = -24f,
                isAtkBuff = false,
                isDefBuff = true,
                isMultiTarget = true,
                isTargetEnemy = false,
                remainTurn = 3,
            },
            new Skill()
            {
                name = "Regeneration 2",
                power = 0,
                type = "passive",
                description = "Heal 4% of max Hp each turn. Require : Level 45",
                hpGain = 0.04f,
                mpGain = 0,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = false,
                remainTurn = 999,
            },
            new Skill()
            {
                name = "super slash 4",
                power = 100,
                type = "physic",
                description = "Deal heavy physic damage to all enemies. Require : Level 50",
                hpGain = 0,
                mpGain = -16f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = true,
                isTargetEnemy = true,
                remainTurn = 0,
            },
        };

        public List<Skill> mageUnobtained = new List<Skill>()
        {
            new Skill()
            {
                name = "Water 1",
                power = 40,
                type = "water",
                description = "Deal light water damage to an enemy. Require : Level 10",
                hpGain = 0,
                mpGain = -4f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = true,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Fire 2",
                power = 40,
                type = "fire",
                description = "Deal light fire damage to all enemies. Require : Level 15",
                hpGain = 0,
                mpGain = -10f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = true,
                isTargetEnemy = true,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "water 2",
                power = 40,
                type = "water",
                description = "Deal light water damage to all enemies. Require : Level 20",
                hpGain = 0,
                mpGain = -10f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = true,
                isTargetEnemy = true,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Invigoration 1",
                power = 0,
                type = "passive",
                description = "Heal 3 Mp each turn. Require : Level 25",
                hpGain = 0,
                mpGain = 3,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = false,
                remainTurn = 999,
            },
            new Skill()
            {
                name = "Fire 3",
                power = 90,
                type = "Fire",
                description = "Deal heavy fire damage to an enemy. Require : Level 30",
                hpGain = 0,
                mpGain = -8f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = true,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Water 3",
                power = 90,
                type = "water",
                description = "Deal heavy water damage to an enemy. Require : Level 35",
                hpGain = 0,
                mpGain = -8f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = true,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Invigoration 2",
                power = 0,
                type = "passive",
                description = "Heal 5 Mp each turn. Require : Level 40",
                hpGain = 0,
                mpGain = 5f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = false,
                remainTurn = 999,
            },
            new Skill()
            {
                name = "Fire 4",
                power = 90,
                type = "fire",
                description = "Deal heavy fire damage to all enemies. Require : Level 45",
                hpGain = 0,
                mpGain = -16f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = true,
                isTargetEnemy = true,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Fire 4",
                power = 90,
                type = "water",
                description = "Deal heavy water damage to all enemies. Require : Level 50",
                hpGain = 0,
                mpGain = -16f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = true,
                isTargetEnemy = true,
                remainTurn = 0,
            },
        };

        public List<Skill> witchUnobtained = new List<Skill>()
        {
            new Skill()
            {
                name = "toxic 1",
                power = 40,
                type = "toxic",
                description = "Deal light toxic damage to an enemy. Require : Level 10",
                hpGain = 0,
                mpGain = -4f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = true,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Attack Buff",
                power = 0,
                type = "buff",
                description = "Increase attack for an ally for 3 turns. Require : Level 15",
                hpGain = 0,
                mpGain = -8f,
                isAtkBuff = true,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = false,
                remainTurn = 3,
            },
            new Skill()
            {
                name = "Heal 2",
                power = 0,
                type = "support",
                description = "Heal 30% of max Hp for all allies. Require : Level 20",
                hpGain = 0.3f,
                mpGain = -7f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = true,
                isTargetEnemy = true,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Invigoration 1",
                power = 0,
                type = "passive",
                description = "Heal 3 Mp each turn. Require : Level 25",
                hpGain = 0,
                mpGain = 3,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = false,
                remainTurn = 999,
            },
            new Skill()
            {
                name = "Toxic 2",
                power = 40,
                type = "toxic",
                description = "Deal heavy toxic damage to all enemies. Require : Level 30",
                hpGain = 0,
                mpGain = -10f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = true,
                isTargetEnemy = true,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Heal 3",
                power = 0,
                type = "support",
                description = "Heal 50% Hp for all allies. Require : Level 35",
                hpGain = 0.5f,
                mpGain = -6f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = true,
                isTargetEnemy = false,
                remainTurn = 0,
            },
            new Skill()
            {
                name = "Attack buff plus",
                power = 0,
                type = "support",
                description = "increase defend for all allies. Require : Level 40",
                hpGain = 0,
                mpGain = -24f,
                isAtkBuff = true,
                isDefBuff = false,
                isMultiTarget = true,
                isTargetEnemy = false,
                remainTurn = 3,
            },
            new Skill()
            {
                name = "Invigoration 2",
                power = 0,
                type = "passive",
                description = "Heal 5 Mp each turn. Require : Level 45",
                hpGain = 0,
                mpGain = 5,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = false,
                isTargetEnemy = false,
                remainTurn = 999,
            },
            new Skill()
            {
                name = "Heal 4",
                power = 100,
                type = "physic",
                description = "Heal 50% Hp for all allies. Require : Level 50",
                hpGain = 0,
                mpGain = -12f,
                isAtkBuff = false,
                isDefBuff = false,
                isMultiTarget = true,
                isTargetEnemy = false,
                remainTurn = 0,
            },
        };
    }
}
